/test-app
    /node_modules
    /public
        /css
            styles.css
        /js
            script.js
        index.html
    /data
        tests.json
        results.json
    server.js
    package.json
